### ISSUE TITLE
IndexError: index 45 is out of bounds for dimension 1 with size 20

### ISSUE THREAD

**Issue by yangt1013** [gaobb/MCAR#2]
=> no checkpoint found at ''
lr: [0.001 0.01 ]
Training:   0%|          | 0/314 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ty/图片/MCAR-master/src/main.py", line 121, in <module>
    main()
  File "/home/ty/图片/MCAR-master/src/main.py", line 116, in main
    engine.learning(model, criterion, train_dataset, val_dataset, optimizer)
  File "/home/ty/图片/MCAR-master/src/engine.py", line 212, in learning
    train_loss, train_gloss, train_lloss, train_map = self.train(train_loader, model, criterion, optimizer, epoch)
  File "/home/ty/图片/MCAR-master/src/engine.py", line 264, in train
    self.on_forward(True, model, criterion, data_loader, optimizer)
  File "/home/ty/图片/MCAR-master/src/engine.py", line 443, in on_forward
    gscore, lscore = model(input_var)
  File "/home/ty/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ty/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/ty/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ty/图片/MCAR-master/src/models.py", line 161, in forward
    xs = wscore[i,gs_ind[j],:].squeeze()
IndexError: index 45 is out of bounds for dimension 1 with size 20

**Comment by yangt1013** [comment]
The problomes as follows,how to solove it?

**Comment by gaobb** [comment]
Please check the number of categories in your dataset.

**Comment by gaobb** [comment]
Please check the number of categories in your dataset.
