### ISSUE TITLE
Getting a file not found issue..

### ISSUE THREAD

**Issue by maniappan** [gaobb/MCAR#3]
On run_demo.sh, I am getting this error, looks like the MCAR_models directory is not being found, let know if I missed some steps..

ubuntu@ip-172-31-90-6:~/MCAR$ ./run_demo.sh 
../MCAR-models/coco2014-resnet101-gwp-448-4-0.5.pth.tar
coco2014
Traceback (most recent call last):
  File "./src/mcar_demo.py", line 141, in <module>
    main()
  File "./src/mcar_demo.py", line 114, in main
    mcar = MCARDemo(args.bm, args.ps, args.topN, args.threshold, args.resume, args.dataset_name, args.image_size)
  File "./src/mcar_demo.py", line 75, in __init__
    checkpoint = torch.load(args.resume)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../MCAR-models/coco2014-resnet101-gwp-448-4-0.5.pth.tar'

**Comment by gaobb** [comment]
You need firstly train a model  (run.sh) and then see visualization based on the trained model(run_demo.sh).
